/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uYKQgQgWR9Ex8gMHqRFTud

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsmj2Go6VeqP4 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Mj2GO6-VeqP4/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsmj2Go6VeqP4
});
