/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uYKQgQgWR9Ex8gMHqRFTud
export const unnamedDataToken = "";
