/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: GTgVzsUHzMuCMexkxJk8C

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: GTgVzsUHzMuCMexkxJk8C/projectModule

import "./plasmic.css"; // plasmic-import: GTgVzsUHzMuCMexkxJk8C/projectcss

const data = {
  base: `${"plasmic_tokens_GTgVzsUHzMuCMexkxJk8C"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
